// Innovation Lab Stakeholders - 15 stakeholders
export const STAKEHOLDERS = {
  CTO: { id: 'CTO', name: 'Chief Technology Officer', role: 'Technology Strategy', archetype: 'VISIONARY', influence: 0.95, initialTrust: 75, initialAlignment: 78, priorities: ['innovationPipeline', 'researchQuality', 'teamCapability'], riskTolerance: 0.70 },
  RD_DIRECTOR: { id: 'RD_DIRECTOR', name: 'R&D Director', role: 'Research Leadership', archetype: 'SCIENTIST', influence: 0.88, initialTrust: 72, initialAlignment: 75, priorities: ['researchQuality', 'teamCapability', 'intellectualProperty'], riskTolerance: 0.65 },
  LEAD_RESEARCHER: { id: 'LEAD_RESEARCHER', name: 'Lead Researcher', role: 'Technical Excellence', archetype: 'EXPERT', influence: 0.75, initialTrust: 70, initialAlignment: 72, priorities: ['researchQuality', 'intellectualProperty', 'teamCapability'], riskTolerance: 0.55 },
  PRODUCT_VP: { id: 'PRODUCT_VP', name: 'VP Product', role: 'Product Strategy', archetype: 'MARKET_DRIVER', influence: 0.82, initialTrust: 65, initialAlignment: 60, priorities: ['marketAlignment', 'innovationPipeline', 'resourceEfficiency'], riskTolerance: 0.60 },
  INNOVATION_HEAD: { id: 'INNOVATION_HEAD', name: 'Innovation Director', role: 'Innovation Process', archetype: 'CATALYST', influence: 0.78, initialTrust: 68, initialAlignment: 70, priorities: ['innovationPipeline', 'partnerEcosystem', 'executiveSupport'], riskTolerance: 0.75 },
  CFO: { id: 'CFO', name: 'Chief Financial Officer', role: 'Financial Oversight', archetype: 'GUARDIAN', influence: 0.90, initialTrust: 60, initialAlignment: 55, priorities: ['resourceEfficiency', 'marketAlignment', 'executiveSupport'], riskTolerance: 0.35 },
  CEO: { id: 'CEO', name: 'Chief Executive Officer', role: 'Executive Sponsor', archetype: 'LEADER', influence: 0.98, initialTrust: 70, initialAlignment: 68, priorities: ['executiveSupport', 'marketAlignment', 'innovationPipeline'], riskTolerance: 0.55 },
  BOARD_TECH: { id: 'BOARD_TECH', name: 'Board Technology Member', role: 'Board Oversight', archetype: 'ADVISOR', influence: 0.85, initialTrust: 58, initialAlignment: 55, priorities: ['innovationPipeline', 'resourceEfficiency', 'intellectualProperty'], riskTolerance: 0.45 },
  STARTUP_PARTNER: { id: 'STARTUP_PARTNER', name: 'Startup Partner', role: 'External Innovation', archetype: 'ENTREPRENEUR', influence: 0.62, initialTrust: 55, initialAlignment: 65, priorities: ['partnerEcosystem', 'innovationPipeline', 'marketAlignment'], riskTolerance: 0.85 },
  UNIVERSITY_PARTNER: { id: 'UNIVERSITY_PARTNER', name: 'University Partner', role: 'Academic Collaboration', archetype: 'ACADEMIC', influence: 0.55, initialTrust: 65, initialAlignment: 70, priorities: ['researchQuality', 'intellectualProperty', 'partnerEcosystem'], riskTolerance: 0.50 },
  IP_COUNSEL: { id: 'IP_COUNSEL', name: 'IP Counsel', role: 'Intellectual Property', archetype: 'PROTECTOR', influence: 0.58, initialTrust: 68, initialAlignment: 65, priorities: ['intellectualProperty', 'researchQuality', 'partnerEcosystem'], riskTolerance: 0.30 },
  TALENT_HEAD: { id: 'TALENT_HEAD', name: 'R&D Talent Head', role: 'Talent Management', archetype: 'DEVELOPER', influence: 0.60, initialTrust: 70, initialAlignment: 68, priorities: ['teamCapability', 'executiveSupport', 'innovationPipeline'], riskTolerance: 0.50 },
  VENTURE_PARTNER: { id: 'VENTURE_PARTNER', name: 'Corporate VC Partner', role: 'Investment Strategy', archetype: 'INVESTOR', influence: 0.65, initialTrust: 55, initialAlignment: 60, priorities: ['partnerEcosystem', 'marketAlignment', 'innovationPipeline'], riskTolerance: 0.75 },
  BUSINESS_UNIT: { id: 'BUSINESS_UNIT', name: 'Business Unit GM', role: 'Commercial Adoption', archetype: 'OPERATOR', influence: 0.72, initialTrust: 58, initialAlignment: 52, priorities: ['marketAlignment', 'resourceEfficiency', 'innovationPipeline'], riskTolerance: 0.45 },
  EMERGING_TECH: { id: 'EMERGING_TECH', name: 'Emerging Tech Lead', role: 'Technology Scouting', archetype: 'EXPLORER', influence: 0.52, initialTrust: 72, initialAlignment: 75, priorities: ['innovationPipeline', 'partnerEcosystem', 'researchQuality'], riskTolerance: 0.80 }
};
export const STAKEHOLDER_COMMITTEES = { INNOVATION_BOARD: ['CEO', 'CTO', 'CFO', 'RD_DIRECTOR'], TECHNICAL_COUNCIL: ['CTO', 'RD_DIRECTOR', 'LEAD_RESEARCHER', 'EMERGING_TECH'], PARTNERSHIP_COUNCIL: ['INNOVATION_HEAD', 'STARTUP_PARTNER', 'UNIVERSITY_PARTNER', 'VENTURE_PARTNER'] };
export const RELATIONSHIP_DYNAMICS = { ALLIANCES: [['CTO', 'RD_DIRECTOR'], ['INNOVATION_HEAD', 'STARTUP_PARTNER']], TENSIONS: [['CFO', 'RD_DIRECTOR'], ['BUSINESS_UNIT', 'LEAD_RESEARCHER']] };
export const getStakeholderById = (id) => STAKEHOLDERS[id];
export const getAllStakeholders = () => Object.values(STAKEHOLDERS);
