// Metamorphosis Stakeholders - 15 stakeholders for transformation
export const STAKEHOLDERS = {
  CEO: { id: 'CEO', name: 'Chief Executive Officer', role: 'Transformation Sponsor', archetype: 'VISIONARY', influence: 0.98, initialTrust: 70, initialAlignment: 72, priorities: ['transformationProgress', 'stakeholderBuyIn', 'valueCapture'], riskTolerance: 0.60 },
  TRANSFORM_LEAD: { id: 'TRANSFORM_LEAD', name: 'Transformation Director', role: 'Change Leadership', archetype: 'CATALYST', influence: 0.88, initialTrust: 72, initialAlignment: 78, priorities: ['transformationProgress', 'executionMomentum', 'changeReadiness'], riskTolerance: 0.70 },
  CTO: { id: 'CTO', name: 'Chief Technology Officer', role: 'Digital Leadership', archetype: 'INNOVATOR', influence: 0.85, initialTrust: 68, initialAlignment: 70, priorities: ['capabilityBuilding', 'transformationProgress', 'executionMomentum'], riskTolerance: 0.65 },
  CHRO: { id: 'CHRO', name: 'Chief HR Officer', role: 'People Transformation', archetype: 'ENABLER', influence: 0.80, initialTrust: 72, initialAlignment: 68, priorities: ['culturalShift', 'changeReadiness', 'resistanceManagement'], riskTolerance: 0.50 },
  CFO: { id: 'CFO', name: 'Chief Financial Officer', role: 'Investment Oversight', archetype: 'GUARDIAN', influence: 0.88, initialTrust: 58, initialAlignment: 52, priorities: ['valueCapture', 'executionMomentum', 'capabilityBuilding'], riskTolerance: 0.35 },
  COO: { id: 'COO', name: 'Chief Operations Officer', role: 'Operational Change', archetype: 'EXECUTOR', influence: 0.82, initialTrust: 65, initialAlignment: 60, priorities: ['executionMomentum', 'transformationProgress', 'valueCapture'], riskTolerance: 0.45 },
  BUSINESS_UNIT_HEAD: { id: 'BUSINESS_UNIT_HEAD', name: 'Business Unit Head', role: 'Unit Transformation', archetype: 'SKEPTIC', influence: 0.75, initialTrust: 52, initialAlignment: 48, priorities: ['valueCapture', 'resistanceManagement', 'stakeholderBuyIn'], riskTolerance: 0.40 },
  CHANGE_CHAMPION: { id: 'CHANGE_CHAMPION', name: 'Change Champion', role: 'Grassroots Change', archetype: 'ADVOCATE', influence: 0.62, initialTrust: 75, initialAlignment: 80, priorities: ['changeReadiness', 'culturalShift', 'stakeholderBuyIn'], riskTolerance: 0.65 },
  UNION_REP: { id: 'UNION_REP', name: 'Union Representative', role: 'Worker Advocacy', archetype: 'PROTECTOR', influence: 0.58, initialTrust: 42, initialAlignment: 38, priorities: ['resistanceManagement', 'stakeholderBuyIn', 'changeReadiness'], riskTolerance: 0.30 },
  BOARD_MEMBER: { id: 'BOARD_MEMBER', name: 'Board Member', role: 'Governance Oversight', archetype: 'OVERSEER', influence: 0.85, initialTrust: 55, initialAlignment: 52, priorities: ['valueCapture', 'transformationProgress', 'stakeholderBuyIn'], riskTolerance: 0.40 },
  EXTERNAL_ADVISOR: { id: 'EXTERNAL_ADVISOR', name: 'Transformation Advisor', role: 'Expert Guidance', archetype: 'EXPERT', influence: 0.68, initialTrust: 58, initialAlignment: 65, priorities: ['transformationProgress', 'capabilityBuilding', 'executionMomentum'], riskTolerance: 0.60 },
  KEY_CUSTOMER: { id: 'KEY_CUSTOMER', name: 'Key Customer', role: 'Customer Voice', archetype: 'CLIENT', influence: 0.60, initialTrust: 50, initialAlignment: 48, priorities: ['valueCapture', 'executionMomentum', 'transformationProgress'], riskTolerance: 0.35 },
  IT_HEAD: { id: 'IT_HEAD', name: 'IT Director', role: 'Technology Enablement', archetype: 'BUILDER', influence: 0.70, initialTrust: 65, initialAlignment: 68, priorities: ['capabilityBuilding', 'transformationProgress', 'executionMomentum'], riskTolerance: 0.55 },
  MIDDLE_MANAGER: { id: 'MIDDLE_MANAGER', name: 'Middle Management Rep', role: 'Implementation Layer', archetype: 'IMPLEMENTER', influence: 0.55, initialTrust: 48, initialAlignment: 45, priorities: ['resistanceManagement', 'changeReadiness', 'stakeholderBuyIn'], riskTolerance: 0.40 },
  COMMS_HEAD: { id: 'COMMS_HEAD', name: 'Communications Director', role: 'Change Communications', archetype: 'MESSENGER', influence: 0.58, initialTrust: 68, initialAlignment: 70, priorities: ['stakeholderBuyIn', 'changeReadiness', 'culturalShift'], riskTolerance: 0.50 }
};
export const STAKEHOLDER_COMMITTEES = { TRANSFORMATION_STEERING: ['CEO', 'TRANSFORM_LEAD', 'CFO', 'CTO', 'CHRO'], CHANGE_NETWORK: ['CHANGE_CHAMPION', 'MIDDLE_MANAGER', 'COMMS_HEAD'] };
export const RELATIONSHIP_DYNAMICS = { ALLIANCES: [['CEO', 'TRANSFORM_LEAD'], ['CTO', 'IT_HEAD']], TENSIONS: [['CFO', 'CTO'], ['BUSINESS_UNIT_HEAD', 'TRANSFORM_LEAD']] };
export const getStakeholderById = (id) => STAKEHOLDERS[id];
export const getAllStakeholders = () => Object.values(STAKEHOLDERS);
