// Nexus Protocol Stakeholders - 15 stakeholders for partnerships
export const STAKEHOLDERS = {
  ALLIANCE_LEAD: { id: 'ALLIANCE_LEAD', name: 'Alliance Director', role: 'Partnership Management', archetype: 'ORCHESTRATOR', influence: 0.88, initialTrust: 72, initialAlignment: 75, priorities: ['partnerAlignment', 'valueCreation', 'governanceEffectiveness'], riskTolerance: 0.60 },
  CEO: { id: 'CEO', name: 'Chief Executive Officer', role: 'Executive Sponsor', archetype: 'LEADER', influence: 0.98, initialTrust: 68, initialAlignment: 70, priorities: ['valueCreation', 'partnerAlignment', 'innovationSynergy'], riskTolerance: 0.55 },
  PARTNER_CEO: { id: 'PARTNER_CEO', name: 'Partner CEO', role: 'Partner Leadership', archetype: 'COUNTERPART', influence: 0.92, initialTrust: 55, initialAlignment: 52, priorities: ['valueCreation', 'trustFoundation', 'partnerAlignment'], riskTolerance: 0.50 },
  CFO: { id: 'CFO', name: 'Chief Financial Officer', role: 'Financial Governance', archetype: 'GUARDIAN', influence: 0.85, initialTrust: 60, initialAlignment: 58, priorities: ['valueCreation', 'exitReadiness', 'governanceEffectiveness'], riskTolerance: 0.35 },
  PARTNER_CFO: { id: 'PARTNER_CFO', name: 'Partner CFO', role: 'Partner Finance', archetype: 'COUNTERPART', influence: 0.78, initialTrust: 52, initialAlignment: 50, priorities: ['valueCreation', 'governanceEffectiveness', 'exitReadiness'], riskTolerance: 0.40 },
  STRATEGY_VP: { id: 'STRATEGY_VP', name: 'VP Strategy', role: 'Strategic Planning', archetype: 'STRATEGIST', influence: 0.75, initialTrust: 68, initialAlignment: 70, priorities: ['partnerAlignment', 'innovationSynergy', 'valueCreation'], riskTolerance: 0.55 },
  OPERATIONS_LEAD: { id: 'OPERATIONS_LEAD', name: 'Operations Integration Lead', role: 'Operational Synergy', archetype: 'INTEGRATOR', influence: 0.70, initialTrust: 70, initialAlignment: 72, priorities: ['operationalIntegration', 'valueCreation', 'partnerAlignment'], riskTolerance: 0.50 },
  LEGAL_COUNSEL: { id: 'LEGAL_COUNSEL', name: 'Partnership Counsel', role: 'Legal Framework', archetype: 'PROTECTOR', influence: 0.68, initialTrust: 65, initialAlignment: 62, priorities: ['governanceEffectiveness', 'exitReadiness', 'conflictManagement'], riskTolerance: 0.25 },
  BOARD_REP: { id: 'BOARD_REP', name: 'Board Representative', role: 'Governance Oversight', archetype: 'OVERSEER', influence: 0.82, initialTrust: 55, initialAlignment: 52, priorities: ['valueCreation', 'governanceEffectiveness', 'exitReadiness'], riskTolerance: 0.40 },
  INNOVATION_LEAD: { id: 'INNOVATION_LEAD', name: 'Innovation Director', role: 'Joint Innovation', archetype: 'INNOVATOR', influence: 0.65, initialTrust: 72, initialAlignment: 75, priorities: ['innovationSynergy', 'partnerAlignment', 'valueCreation'], riskTolerance: 0.70 },
  PARTNER_OPS: { id: 'PARTNER_OPS', name: 'Partner Operations Lead', role: 'Partner Operations', archetype: 'COUNTERPART', influence: 0.62, initialTrust: 58, initialAlignment: 55, priorities: ['operationalIntegration', 'conflictManagement', 'partnerAlignment'], riskTolerance: 0.45 },
  KEY_CUSTOMER: { id: 'KEY_CUSTOMER', name: 'Joint Customer', role: 'Customer Voice', archetype: 'CLIENT', influence: 0.58, initialTrust: 50, initialAlignment: 52, priorities: ['valueCreation', 'operationalIntegration', 'trustFoundation'], riskTolerance: 0.35 },
  COMMS_LEAD: { id: 'COMMS_LEAD', name: 'Partnership Communications', role: 'Stakeholder Communications', archetype: 'MESSENGER', influence: 0.52, initialTrust: 68, initialAlignment: 70, priorities: ['trustFoundation', 'partnerAlignment', 'conflictManagement'], riskTolerance: 0.50 },
  ECOSYSTEM_MGR: { id: 'ECOSYSTEM_MGR', name: 'Ecosystem Manager', role: 'Partner Network', archetype: 'NETWORKER', influence: 0.55, initialTrust: 70, initialAlignment: 72, priorities: ['partnerAlignment', 'innovationSynergy', 'operationalIntegration'], riskTolerance: 0.60 },
  RISK_MANAGER: { id: 'RISK_MANAGER', name: 'Partnership Risk Manager', role: 'Risk Management', archetype: 'ANALYZER', influence: 0.58, initialTrust: 65, initialAlignment: 60, priorities: ['exitReadiness', 'conflictManagement', 'governanceEffectiveness'], riskTolerance: 0.30 }
};
export const STAKEHOLDER_COMMITTEES = { ALLIANCE_BOARD: ['CEO', 'PARTNER_CEO', 'CFO', 'PARTNER_CFO'], OPERATIONS_COMMITTEE: ['OPERATIONS_LEAD', 'PARTNER_OPS', 'INNOVATION_LEAD'] };
export const RELATIONSHIP_DYNAMICS = { ALLIANCES: [['ALLIANCE_LEAD', 'STRATEGY_VP'], ['INNOVATION_LEAD', 'ECOSYSTEM_MGR']], TENSIONS: [['CFO', 'PARTNER_CFO'], ['LEGAL_COUNSEL', 'INNOVATION_LEAD']] };
export const getStakeholderById = (id) => STAKEHOLDERS[id];
export const getAllStakeholders = () => Object.values(STAKEHOLDERS);
