// Crucible Stakeholders - 15 stakeholders for crisis leadership
export const STAKEHOLDERS = {
  CEO: { id: 'CEO', name: 'Chief Executive Officer', role: 'Crisis Commander', archetype: 'LEADER', influence: 0.98, initialTrust: 68, initialAlignment: 70, priorities: ['crisisControl', 'stakeholderConfidence', 'strategicClarity'], riskTolerance: 0.60 },
  BOARD_CHAIR: { id: 'BOARD_CHAIR', name: 'Board Chairman', role: 'Governance', archetype: 'OVERSEER', influence: 0.95, initialTrust: 55, initialAlignment: 52, priorities: ['stakeholderConfidence', 'reputationHealth', 'crisisControl'], riskTolerance: 0.40 },
  CFO: { id: 'CFO', name: 'Chief Financial Officer', role: 'Financial Stability', archetype: 'GUARDIAN', influence: 0.88, initialTrust: 65, initialAlignment: 62, priorities: ['resourceReserves', 'operationalContinuity', 'stakeholderConfidence'], riskTolerance: 0.35 },
  COO: { id: 'COO', name: 'Chief Operations Officer', role: 'Operational Continuity', archetype: 'EXECUTOR', influence: 0.85, initialTrust: 70, initialAlignment: 68, priorities: ['operationalContinuity', 'teamResilience', 'crisisControl'], riskTolerance: 0.55 },
  CRISIS_LEAD: { id: 'CRISIS_LEAD', name: 'Crisis Response Lead', role: 'Crisis Management', archetype: 'COMMANDER', influence: 0.80, initialTrust: 72, initialAlignment: 75, priorities: ['crisisControl', 'communicationEffectiveness', 'operationalContinuity'], riskTolerance: 0.70 },
  COMMS_VP: { id: 'COMMS_VP', name: 'VP Communications', role: 'Stakeholder Communications', archetype: 'MESSENGER', influence: 0.75, initialTrust: 65, initialAlignment: 68, priorities: ['communicationEffectiveness', 'reputationHealth', 'stakeholderConfidence'], riskTolerance: 0.45 },
  LEGAL_COUNSEL: { id: 'LEGAL_COUNSEL', name: 'General Counsel', role: 'Legal Protection', archetype: 'PROTECTOR', influence: 0.78, initialTrust: 62, initialAlignment: 60, priorities: ['crisisControl', 'reputationHealth', 'resourceReserves'], riskTolerance: 0.25 },
  HR_HEAD: { id: 'HR_HEAD', name: 'Chief People Officer', role: 'Employee Welfare', archetype: 'SUPPORTER', influence: 0.70, initialTrust: 72, initialAlignment: 70, priorities: ['teamResilience', 'communicationEffectiveness', 'operationalContinuity'], riskTolerance: 0.50 },
  KEY_INVESTOR: { id: 'KEY_INVESTOR', name: 'Lead Investor', role: 'Capital Stakeholder', archetype: 'FINANCIER', influence: 0.82, initialTrust: 48, initialAlignment: 45, priorities: ['stakeholderConfidence', 'resourceReserves', 'strategicClarity'], riskTolerance: 0.40 },
  MAJOR_CUSTOMER: { id: 'MAJOR_CUSTOMER', name: 'Major Customer Exec', role: 'Customer Voice', archetype: 'CLIENT', influence: 0.68, initialTrust: 50, initialAlignment: 48, priorities: ['operationalContinuity', 'reputationHealth', 'stakeholderConfidence'], riskTolerance: 0.30 },
  UNION_REP: { id: 'UNION_REP', name: 'Union Representative', role: 'Worker Advocacy', archetype: 'ADVOCATE', influence: 0.62, initialTrust: 45, initialAlignment: 42, priorities: ['teamResilience', 'operationalContinuity', 'communicationEffectiveness'], riskTolerance: 0.35 },
  REGULATOR: { id: 'REGULATOR', name: 'Regulatory Contact', role: 'Regulatory Compliance', archetype: 'AUTHORITY', influence: 0.72, initialTrust: 52, initialAlignment: 50, priorities: ['crisisControl', 'communicationEffectiveness', 'reputationHealth'], riskTolerance: 0.20 },
  MEDIA_CONTACT: { id: 'MEDIA_CONTACT', name: 'Key Media Contact', role: 'Media Relations', archetype: 'NARRATOR', influence: 0.58, initialTrust: 40, initialAlignment: 38, priorities: ['reputationHealth', 'communicationEffectiveness', 'stakeholderConfidence'], riskTolerance: 0.50 },
  STRATEGY_HEAD: { id: 'STRATEGY_HEAD', name: 'Strategy Director', role: 'Strategic Planning', archetype: 'STRATEGIST', influence: 0.65, initialTrust: 68, initialAlignment: 70, priorities: ['strategicClarity', 'crisisControl', 'stakeholderConfidence'], riskTolerance: 0.55 },
  SECURITY_CHIEF: { id: 'SECURITY_CHIEF', name: 'Security Chief', role: 'Security Operations', archetype: 'DEFENDER', influence: 0.60, initialTrust: 70, initialAlignment: 72, priorities: ['crisisControl', 'operationalContinuity', 'resourceReserves'], riskTolerance: 0.45 }
};
export const STAKEHOLDER_COMMITTEES = { CRISIS_TEAM: ['CEO', 'CRISIS_LEAD', 'COO', 'COMMS_VP', 'LEGAL_COUNSEL'], BOARD_CRISIS: ['BOARD_CHAIR', 'CEO', 'CFO', 'KEY_INVESTOR'] };
export const RELATIONSHIP_DYNAMICS = { ALLIANCES: [['CEO', 'CRISIS_LEAD'], ['COO', 'HR_HEAD']], TENSIONS: [['UNION_REP', 'CFO'], ['MEDIA_CONTACT', 'LEGAL_COUNSEL']] };
export const getStakeholderById = (id) => STAKEHOLDERS[id];
export const getAllStakeholders = () => Object.values(STAKEHOLDERS);
