// Margin Call Stakeholders - 15 stakeholders for financial crisis
export const STAKEHOLDERS = {
  CFO: { id: 'CFO', name: 'Chief Financial Officer', role: 'Financial Crisis Lead', archetype: 'CRISIS_MANAGER', influence: 0.95, initialTrust: 65, initialAlignment: 70, priorities: ['liquidityPosition', 'debtManagement', 'operationalCashflow'], riskTolerance: 0.50 },
  CEO: { id: 'CEO', name: 'Chief Executive Officer', role: 'Executive Leadership', archetype: 'LEADER', influence: 0.98, initialTrust: 60, initialAlignment: 65, priorities: ['investorConfidence', 'marketPosition', 'recoveryTrajectory'], riskTolerance: 0.55 },
  TREASURER: { id: 'TREASURER', name: 'Treasurer', role: 'Liquidity Management', archetype: 'GUARDIAN', influence: 0.82, initialTrust: 72, initialAlignment: 75, priorities: ['liquidityPosition', 'operationalCashflow', 'debtManagement'], riskTolerance: 0.35 },
  LEAD_BANKER: { id: 'LEAD_BANKER', name: 'Lead Investment Banker', role: 'Restructuring Advisor', archetype: 'ADVISOR', influence: 0.78, initialTrust: 55, initialAlignment: 52, priorities: ['debtManagement', 'creditorRelations', 'recoveryTrajectory'], riskTolerance: 0.60 },
  SENIOR_CREDITOR: { id: 'SENIOR_CREDITOR', name: 'Senior Secured Creditor', role: 'Priority Creditor', archetype: 'ENFORCER', influence: 0.88, initialTrust: 40, initialAlignment: 35, priorities: ['creditorRelations', 'liquidityPosition', 'debtManagement'], riskTolerance: 0.25 },
  UNSECURED_CREDITOR: { id: 'UNSECURED_CREDITOR', name: 'Unsecured Creditor Rep', role: 'Creditor Committee', archetype: 'CLAIMANT', influence: 0.70, initialTrust: 35, initialAlignment: 32, priorities: ['creditorRelations', 'recoveryTrajectory', 'debtManagement'], riskTolerance: 0.30 },
  BOARD_CHAIR: { id: 'BOARD_CHAIR', name: 'Board Chairman', role: 'Governance Oversight', archetype: 'OVERSEER', influence: 0.92, initialTrust: 52, initialAlignment: 48, priorities: ['investorConfidence', 'debtManagement', 'recoveryTrajectory'], riskTolerance: 0.40 },
  EQUITY_HOLDER: { id: 'EQUITY_HOLDER', name: 'Major Equity Holder', role: 'Shareholder Interest', archetype: 'OWNER', influence: 0.75, initialTrust: 45, initialAlignment: 42, priorities: ['investorConfidence', 'recoveryTrajectory', 'marketPosition'], riskTolerance: 0.50 },
  COO: { id: 'COO', name: 'Chief Operations Officer', role: 'Operational Continuity', archetype: 'OPERATOR', influence: 0.80, initialTrust: 68, initialAlignment: 70, priorities: ['operationalCashflow', 'marketPosition', 'liquidityPosition'], riskTolerance: 0.45 },
  LEGAL_COUNSEL: { id: 'LEGAL_COUNSEL', name: 'Restructuring Counsel', role: 'Legal Strategy', archetype: 'PROTECTOR', influence: 0.72, initialTrust: 65, initialAlignment: 62, priorities: ['creditorRelations', 'debtManagement', 'riskExposure'], riskTolerance: 0.30 },
  KEY_SUPPLIER: { id: 'KEY_SUPPLIER', name: 'Key Supplier', role: 'Supply Continuity', archetype: 'PARTNER', influence: 0.55, initialTrust: 42, initialAlignment: 40, priorities: ['operationalCashflow', 'creditorRelations', 'liquidityPosition'], riskTolerance: 0.35 },
  EMPLOYEE_REP: { id: 'EMPLOYEE_REP', name: 'Employee Representative', role: 'Employee Interests', archetype: 'ADVOCATE', influence: 0.52, initialTrust: 50, initialAlignment: 48, priorities: ['operationalCashflow', 'recoveryTrajectory', 'marketPosition'], riskTolerance: 0.40 },
  TURNAROUND_EXPERT: { id: 'TURNAROUND_EXPERT', name: 'Turnaround Consultant', role: 'Restructuring Expert', archetype: 'EXPERT', influence: 0.68, initialTrust: 58, initialAlignment: 60, priorities: ['recoveryTrajectory', 'operationalCashflow', 'debtManagement'], riskTolerance: 0.65 },
  REGULATOR: { id: 'REGULATOR', name: 'Financial Regulator', role: 'Regulatory Oversight', archetype: 'AUTHORITY', influence: 0.70, initialTrust: 48, initialAlignment: 45, priorities: ['riskExposure', 'creditorRelations', 'debtManagement'], riskTolerance: 0.15 },
  MEDIA_ANALYST: { id: 'MEDIA_ANALYST', name: 'Financial Media Analyst', role: 'Market Perception', archetype: 'OBSERVER', influence: 0.50, initialTrust: 42, initialAlignment: 40, priorities: ['investorConfidence', 'marketPosition', 'recoveryTrajectory'], riskTolerance: 0.45 }
};
export const STAKEHOLDER_COMMITTEES = { CREDITOR_COMMITTEE: ['SENIOR_CREDITOR', 'UNSECURED_CREDITOR', 'LEAD_BANKER'], RESTRUCTURING_TEAM: ['CFO', 'TREASURER', 'LEGAL_COUNSEL', 'TURNAROUND_EXPERT'] };
export const RELATIONSHIP_DYNAMICS = { ALLIANCES: [['CFO', 'TREASURER'], ['LEAD_BANKER', 'TURNAROUND_EXPERT']], TENSIONS: [['EQUITY_HOLDER', 'SENIOR_CREDITOR'], ['COO', 'KEY_SUPPLIER']] };
export const getStakeholderById = (id) => STAKEHOLDERS[id];
export const getAllStakeholders = () => Object.values(STAKEHOLDERS);
