// Entangled Stakeholders - 15 stakeholders for complex stakeholder dynamics
export const STAKEHOLDERS = {
  INTEGRATION_LEAD: { id: 'INTEGRATION_LEAD', name: 'Integration Director', role: 'Integration Management', archetype: 'ORCHESTRATOR', influence: 0.88, initialTrust: 68, initialAlignment: 72, priorities: ['stakeholderAlignment', 'operationalSynergy', 'valueRealization'], riskTolerance: 0.60 },
  ACQUIRER_CEO: { id: 'ACQUIRER_CEO', name: 'Acquirer CEO', role: 'Acquiring Leadership', archetype: 'DOMINANT', influence: 0.95, initialTrust: 65, initialAlignment: 75, priorities: ['valueRealization', 'decisionVelocity', 'stakeholderAlignment'], riskTolerance: 0.55 },
  TARGET_CEO: { id: 'TARGET_CEO', name: 'Target CEO', role: 'Target Leadership', archetype: 'DISPLACED', influence: 0.75, initialTrust: 45, initialAlignment: 40, priorities: ['culturalIntegration', 'trustLevel', 'stakeholderAlignment'], riskTolerance: 0.40 },
  ACQUIRER_CFO: { id: 'ACQUIRER_CFO', name: 'Acquirer CFO', role: 'Financial Integration', archetype: 'CONTROLLER', influence: 0.82, initialTrust: 62, initialAlignment: 68, priorities: ['valueRealization', 'operationalSynergy', 'decisionVelocity'], riskTolerance: 0.35 },
  TARGET_CHRO: { id: 'TARGET_CHRO', name: 'Target CHRO', role: 'People Integration', archetype: 'PROTECTOR', influence: 0.70, initialTrust: 48, initialAlignment: 42, priorities: ['culturalIntegration', 'trustLevel', 'conflictResolution'], riskTolerance: 0.45 },
  BOARD_REP: { id: 'BOARD_REP', name: 'Board Representative', role: 'Board Oversight', archetype: 'GOVERNOR', influence: 0.85, initialTrust: 55, initialAlignment: 52, priorities: ['valueRealization', 'stakeholderAlignment', 'communicationClarity'], riskTolerance: 0.40 },
  KEY_CUSTOMER: { id: 'KEY_CUSTOMER', name: 'Key Customer', role: 'Customer Continuity', archetype: 'CLIENT', influence: 0.65, initialTrust: 50, initialAlignment: 48, priorities: ['operationalSynergy', 'communicationClarity', 'trustLevel'], riskTolerance: 0.30 },
  UNION_LEADER: { id: 'UNION_LEADER', name: 'Union Leader', role: 'Labor Relations', archetype: 'ADVOCATE', influence: 0.62, initialTrust: 38, initialAlignment: 35, priorities: ['trustLevel', 'conflictResolution', 'culturalIntegration'], riskTolerance: 0.25 },
  KEY_EXECUTIVE_A: { id: 'KEY_EXECUTIVE_A', name: 'Acquirer Key Executive', role: 'Integration Champion', archetype: 'CHAMPION', influence: 0.72, initialTrust: 70, initialAlignment: 75, priorities: ['stakeholderAlignment', 'decisionVelocity', 'operationalSynergy'], riskTolerance: 0.60 },
  KEY_EXECUTIVE_T: { id: 'KEY_EXECUTIVE_T', name: 'Target Key Executive', role: 'Transition Leader', archetype: 'BRIDGE', influence: 0.68, initialTrust: 52, initialAlignment: 48, priorities: ['culturalIntegration', 'trustLevel', 'conflictResolution'], riskTolerance: 0.50 },
  INVESTOR: { id: 'INVESTOR', name: 'Major Investor', role: 'Investment Oversight', archetype: 'FINANCIER', influence: 0.78, initialTrust: 58, initialAlignment: 62, priorities: ['valueRealization', 'decisionVelocity', 'stakeholderAlignment'], riskTolerance: 0.45 },
  REGULATOR: { id: 'REGULATOR', name: 'Regulatory Authority', role: 'Compliance Oversight', archetype: 'AUTHORITY', influence: 0.70, initialTrust: 55, initialAlignment: 50, priorities: ['communicationClarity', 'operationalSynergy', 'stakeholderAlignment'], riskTolerance: 0.20 },
  SUPPLIER_KEY: { id: 'SUPPLIER_KEY', name: 'Key Supplier', role: 'Supply Continuity', archetype: 'PARTNER', influence: 0.55, initialTrust: 52, initialAlignment: 55, priorities: ['operationalSynergy', 'trustLevel', 'communicationClarity'], riskTolerance: 0.40 },
  COMMS_HEAD: { id: 'COMMS_HEAD', name: 'Communications Head', role: 'Integration Communications', archetype: 'MESSENGER', influence: 0.60, initialTrust: 65, initialAlignment: 68, priorities: ['communicationClarity', 'stakeholderAlignment', 'trustLevel'], riskTolerance: 0.50 },
  CULTURE_LEAD: { id: 'CULTURE_LEAD', name: 'Culture Integration Lead', role: 'Culture Harmonization', archetype: 'HARMONIZER', influence: 0.58, initialTrust: 62, initialAlignment: 65, priorities: ['culturalIntegration', 'conflictResolution', 'trustLevel'], riskTolerance: 0.55 }
};
export const STAKEHOLDER_COMMITTEES = { INTEGRATION_STEERING: ['ACQUIRER_CEO', 'TARGET_CEO', 'INTEGRATION_LEAD', 'BOARD_REP'], PEOPLE_INTEGRATION: ['TARGET_CHRO', 'CULTURE_LEAD', 'UNION_LEADER', 'KEY_EXECUTIVE_T'] };
export const RELATIONSHIP_DYNAMICS = { ALLIANCES: [['ACQUIRER_CEO', 'KEY_EXECUTIVE_A'], ['TARGET_CEO', 'KEY_EXECUTIVE_T']], TENSIONS: [['ACQUIRER_CFO', 'TARGET_CHRO'], ['KEY_EXECUTIVE_A', 'KEY_EXECUTIVE_T']] };
export const getStakeholderById = (id) => STAKEHOLDERS[id];
export const getAllStakeholders = () => Object.values(STAKEHOLDERS);
